"""Two executors over the one stage registry.

LocalExecutor runs the resolved stages in sequence in-process (laptop). SnakemakeExecutor
generates a Snakefile from the SAME registry whose rules shell out to ``microfgt _run-stage``
(HTCF batch via a Slurm profile). Neither re-encodes commands — that lives once in the
registry — so the two deployment contexts can't drift.
"""

from __future__ import annotations

from pathlib import Path

from microfgt.stages.model import artifact_paths
from microfgt.stages.registry import execute_stage


class LocalExecutor:
    """Run resolved stages sequentially in-process."""

    def run(self, stages, workdir, config, output=None) -> str:
        Path(workdir).mkdir(parents=True, exist_ok=True)
        for stage in stages:
            execute_stage(stage.id, workdir, config, output)
        return artifact_paths(workdir, config, output)["mudata"]


class SnakemakeExecutor:
    """Generate a Snakefile from the registry (real Slurm execution = HTCF validation IOU)."""

    def generate(self, stages, config_path, workdir, output=None) -> str:
        # config must be on disk so each `_run-stage` shell call can re-read it.
        import re
        import shlex

        from microfgt.orchestrate.cutadapt import discover_pairs
        from microfgt.stages.registry import provided_artifacts
        from microfgt.stages.model import DIRECTORY_ARTIFACTS, scatter_files
        from microfgt.config import load_config

        config = load_config(config_path)
        paths = artifact_paths(workdir, config, output)
        provided = set(provided_artifacts(config))

        # Artifacts produced per-sample (by a scatter stage). A stage consuming one of these must
        # gather (expand over every sample); a scatter stage producing one emits per-sample files.
        scatter_artifacts = {out for s in stages if s.scatter for out in s.outputs}

        # Enumerate samples (+ their read basenames) for the scatter chain. Every scatter stage
        # today roots at the provided shotgun reads (sg_reads); fastp/host-removal keep filenames,
        # so a sample's R1/R2 basenames stay constant down the chain.
        samples: dict[str, tuple] = {}
        if any(s.scatter for s in stages):
            reads_key = "sg_reads" if "sg_reads" in paths else "fastq_dir"
            for sample, r1, r2 in discover_pairs(paths[reads_key]):
                from pathlib import Path as _P
                samples[sample] = (str(r1), str(r2) if r2 else None,
                                   _P(r1).name, _P(r2).name if r2 else None)

        def lit(path) -> str:
            """A path as a Python string literal for an input:/output: field (repr handles any
            special char, incl. spaces, safely)."""
            return repr(str(path))

        def out_item(key) -> str:
            # Directory artifacts must be wrapped in directory() or Snakemake calls them missing.
            return f"directory({lit(paths[key])})" if key in DIRECTORY_ARTIFACTS else lit(paths[key])

        def per_sample_inputs(artifact_key, sample) -> list[str]:
            r1, r2, r1n, r2n = samples[sample]
            if artifact_key in scatter_artifacts:                 # produced per-sample upstream
                return scatter_files(artifact_key, workdir, sample, r1n, r2n)
            return [r1] + ([r2] if r2 else [])                    # the entry reads themselves

        def gather_inputs(artifact_key) -> list[str]:
            files = []
            for sample, (_r1, _r2, r1n, r2n) in samples.items():
                files += scatter_files(artifact_key, workdir, sample, r1n, r2n)
            return files

        def shell_cmd(stage_id, sample=None) -> str:
            # shlex.quote every interpolated path so real paths (spaces, metachars) survive.
            argv = ["microfgt", "_run-stage", stage_id,
                    "--workdir", shlex.quote(str(workdir)),
                    "--config", shlex.quote(str(config_path)),
                    "--output", shlex.quote(str(paths["mudata"]))]
            if sample is not None:
                argv += ["--sample", shlex.quote(sample)]
            return " ".join(argv)

        lines = [
            "# Generated by microFGT from the stage registry — do not edit by hand.",
            "# Each rule shells out to `microfgt _run-stage` so command logic lives once.",
            "# Scatter stages emit one rule per sample so the cluster fans them out.",
            "",
            "rule all:",
            f"    input: {lit(paths['mudata'])}",
            "",
        ]
        for stage in stages:
            if stage.scatter:
                # One job per sample — true per-sample cluster parallelism.
                for sample in samples:
                    ins = [f for k in stage.inputs for f in per_sample_inputs(k, sample)]
                    outs = [f for k in stage.outputs for f in scatter_files(
                        k, workdir, sample, samples[sample][2], samples[sample][3])]
                    safe = re.sub(r"\W", "_", sample)
                    rule = f"{stage.id}_{safe}"
                    lines += [
                        f"rule {rule}:",
                        "    input: " + ", ".join(lit(f) for f in ins),
                        "    output: " + ", ".join(lit(f) for f in outs),
                        f"    shell: {shell_cmd(stage.id, sample)!r}",
                        "",
                    ]
            else:
                # A consumer of a scatter artifact gathers every per-sample file (expand).
                ins = []
                for k in stage.inputs:
                    ins += ([lit(f) for f in gather_inputs(k)] if k in scatter_artifacts
                            else [lit(paths[k])])
                outs = [out_item(k) for k in stage.outputs]
                lines += [
                    f"rule {stage.id}:",
                    "    input: " + ", ".join(ins),
                    "    output: " + ", ".join(outs),
                    f"    shell: {shell_cmd(stage.id)!r}",
                    "",
                ]
        # Provided (entry-point) artifacts are pre-existing inputs with no rule — noted only.
        if provided:
            lines.append("# Entry-point inputs (provided, not generated): " + ", ".join(sorted(provided)))
        return "\n".join(lines)

    def run(self, stages, config_path, workdir, output=None) -> str:
        """Write the Snakefile and return its path. Submitting it (Slurm) is the HTCF step."""
        Path(workdir).mkdir(parents=True, exist_ok=True)
        snakefile = Path(workdir) / "Snakefile"
        snakefile.write_text(self.generate(stages, config_path, workdir, output))
        return str(snakefile)
