"""The stage model — the single source of truth both executors consume.

A stage is a pure file->file step: ``(input artifact paths) -> command -> (output artifact
paths)``. That shape is simultaneously what a make-style local resolver needs and exactly a
Snakemake rule, so the local and cluster executors are two consumers of ONE registry rather
than two hand-maintained DAGs (no drift).

Artifacts are identified by key; generated artifacts get a deterministic path inside the run
workdir, provided artifacts (the entry point) keep their real paths.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

# Artifact key -> default filename inside the workdir. None = provided-only (an entry point
# input or the final output), never generated by a stage into the workdir.
ARTIFACT_FILENAMES: dict[str, str | None] = {
    "fastq_dir": None,               # provided: raw amplicon FASTQs
    "valencia_output": None,         # provided: an existing VALENCIA CSV
    "phyloseq_rds": None,            # provided: a phyloseq .rds (composition + taxonomy + CST)
    "phyloseq_cst": None,            # provided: signal to take CST from the phyloseq (= the .rds)
    "trimmed_reads": "trimmed",      # dir of primer-trimmed FASTQs
    "asv_table": "asv_table.csv",
    "asv_seqs": "asv_seqs.fasta",
    "quality_profile": "quality_profile.tsv",
    "speciateit_results": "speciateit/MC_order7_results.txt",
    "composition": "composition.h5ad",
    "cst": "cst.csv",
    # --- metagenomics (shotgun) arm ---
    "sg_reads": None,                # provided: raw shotgun paired FASTQs
    "vista_output": None,            # provided: an existing VISTA mgCSTs_*.csv
    "sg_trimmed": "mg_trimmed",      # dir of fastp-trimmed FASTQs
    "sg_nonhost": "mg_nonhost",      # dir of host-removed FASTQs
    "sg_virgo2_out": "mg_virgo2_out",  # dir of per-sample VIRGO2 .out files
    # The compiled matrix lives in its OWN dir, a sibling of mg_virgo2_out — NOT inside it.
    # A file output nested in another rule's directory() output is a Snakemake ChildIOException
    # (the compile rule's output would sit under the map rule's directory output).
    "sg_compiled": "mg_compiled/VIRGO2_Compiled.summary.NR.txt",
    "function": "function.h5ad",     # gene x sample (VIRGO2) modality
    "mgcst": "mgcst.csv",            # sample-keyed mgCST call
    "mudata": None,                  # the final target (= config 'output' / CLI -o)
}

# Artifacts that are DIRECTORIES rather than single files. Snakemake needs these wrapped in
# ``directory(...)`` in a rule's ``output:`` — declared as a plain file, Snakemake reports the
# output "missing" after the rule runs (it checks for a file at that path) and the DAG breaks.
# The local executor doesn't care (it just runs stages in order), which is why this only bit the
# cluster path. Kept here, beside the filenames, so the two stay in sync.
DIRECTORY_ARTIFACTS: frozenset[str] = frozenset(
    {"trimmed_reads", "sg_trimmed", "sg_nonhost", "sg_virgo2_out"}
)


@dataclass(frozen=True)
class Requirement:
    """An external prerequisite a stage needs (checked by ``microfgt check``)."""

    kind: str            # "binary" | "rpackage" | "path" | "checksum"
    name: str            # command name, R package name, or filesystem path
    hint: str = ""       # how to satisfy it, shown when missing
    via: str = ""        # rpackage: the Rscript (configured path) to verify the package with
    expected: str = ""   # checksum: the expected sha256 of `name`


@dataclass
class StageContext:
    """Resolved paths + config handed to a stage at execution time."""

    workdir: Path
    artifacts: dict[str, str]   # artifact key -> resolved path
    config: dict
    sample: str | None = None   # set for a per-sample (scatter) execution; None = process all

    def path(self, key: str) -> Path:
        return Path(self.artifacts[key])


@dataclass
class Stage:
    """One file->file step in the workflow."""

    id: str
    inputs: tuple[str, ...]
    outputs: tuple[str, ...]
    run: Callable[[StageContext], None]
    requirements: Callable[[dict], list[Requirement]] = field(
        default=lambda cfg: []
    )
    # A scatter stage runs once per sample (embarrassingly parallel). The local executor still
    # runs it once and loops samples internally; the Snakemake executor emits one job per sample
    # so the cluster actually fans them out. A stage's run fn honours ``ctx.sample`` when set.
    scatter: bool = False


def scatter_files(artifact_key: str, workdir, sample: str, r1_name: str, r2_name: str) -> list[str]:
    """Concrete per-sample files a scatter artifact holds for one sample.

    fastp and host-removal keep each read's filename, so a sample's R1/R2 basenames stay constant
    down the trim -> host-removal chain — which lets the Snakemake generator name every per-sample
    file up front. ``r1_name``/``r2_name`` are those basenames (from ``discover_pairs`` on the
    entry FASTQ dir).
    """
    d = Path(workdir) / ARTIFACT_FILENAMES[artifact_key]
    if artifact_key in ("trimmed_reads", "sg_trimmed", "sg_nonhost"):
        return [str(d / n) for n in (r1_name, r2_name) if n]
    if artifact_key == "sg_virgo2_out":
        return [str(d / f"{sample}.out")]
    raise KeyError(f"{artifact_key} is not a per-sample scatter artifact")


def artifact_paths(workdir, config: dict, output: str | None = None) -> dict[str, str]:
    """Map every artifact key to a concrete path: provided ones from config, the rest under
    the workdir. Both executors call this so they agree on every file location."""
    from microfgt.stages.registry import provided_artifacts

    paths = dict(provided_artifacts(config))
    target = output or config.get("output")
    if target:
        paths["mudata"] = str(target)
    workdir = Path(workdir)
    for key, filename in ARTIFACT_FILENAMES.items():
        if key not in paths and filename is not None:
            paths[key] = str(workdir / filename)
    return paths
